# Generated by Django 4.2.23 on 2026-09-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Başlangıç'), ('intermediate', 'Orta'), ('advanced', 'İleri'), ('expert', 'Uzman')], max_length=50),
        ),
    ]
